const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src', 'ralph', 'RalphSidebarHtml.js');
let content = fs.readFileSync(filePath, 'utf8');

// 1. Update function signature and insert locales
const topReplacement = `const crypto = require('crypto');

const translations = {
    en: {
        update_available: "🆕 Update Available",
        update_now: "⬆ Update Now",
        error_occurred: "❌ Error Occurred",
        on_auto_accept: "ON - Auto Accept Active",
        off: "OFF",
        idle: "IDLE",
        running: "RUNNING",
        quota_paused: "QUOTA PAUSED",
        stopping: "STOPPING...",
        current_iteration: "Current Iteration",
        start: "▶ Start",
        stop: "⏹ Stop",
        task_queue: "📬 Task Queue",
        task_placeholder: "Enter next task...",
        enqueue_task: "📥 Enqueue Task",
        start_task: "🚀 Start Task",
        no_queued_tasks: "No queued tasks",
        task_file: "📋 Task File",
        not_selected: "Not selected",
        sample_prd: "📝 Generate Sample PRD",
        prd_changes: "📝 PRD Changes",
        live_logs: "📜 Live Logs",
        no_logs: "No logs yet",
        ai_quota: "🔋 AI Quota",
        refresh: "🔄",
        connecting: "Connecting...",
        loading_data: "Loading data...",
        no_models: "No models in use",
        reset_calc: "⏱ Reset: calculating...",
        reset_done: "⏱ Reset complete (waiting info)",
        reset_eta: "⏱ Reset in %h h %m m",
        tg_connect: "📡 Connect Telegram",
        tg_disconnect: "📡 Disconnect Telegram",
        tg_detail: "📬 Get Detailed Notifications",
        save: "💾 Save",
        settings: "⚙ Settings",
        max_iter: "Max Iterations",
        iter_delay: "Iteration Delay (sec)",
        allow_prd_mod: "Allow PRD Modification",
        auto_start: "🚀 Auto-start on PRD change",
        auto_commit: "🌿 Git Auto Commit (branch & merge)",
        auto_del_branch: "🗑 Auto Delete Branch (after merge)",
        code_review: "📝 Code Review (Gemini Flash)",
        auto_push: "🚀 Auto Push (on session end)",
        auto_install: "⬆ Auto Install Updates",
        check_updates: "🔍 Check Updates",
        no_git_cred: "⚠ No Git Credentials - auto update disabled.",
        write_prd_ws: "📋 write-prd (Workspace)",
        write_prd_global: "📋 write-prd (Global)",
        consecutive_errors: "%err (Consecutive %cnt)",
        tasks_progress: "%completed / %total tasks (%pct%)",
        update_to: "v%old -> v%new",
        update_btn: "⬆ Update v%version",
        media_attached: " 📎%cnt",
        iteration_log: "Iteration %iter",
        added_log: "+%add",
        removed_log: "-%rem"
    },
    ko: {
        update_available: "🆕 업데이트 가능",
        update_now: "⬆ 지금 업데이트",
        error_occurred: "❌ 에러 발생",
        on_auto_accept: "ON — 자동 수락 활성",
        off: "OFF",
        idle: "IDLE",
        running: "RUNNING",
        quota_paused: "QUOTA PAUSED",
        stopping: "STOPPING...",
        current_iteration: "현재 반복",
        start: "▶ 시작",
        stop: "⏹ 정지",
        task_queue: "📬 작업 큐",
        task_placeholder: "다음 작업 내용을 입력하세요...",
        enqueue_task: "📥 작업 예약",
        start_task: "🚀 작업 시작",
        no_queued_tasks: "예약된 작업이 없습니다",
        task_file: "📋 작업 파일",
        not_selected: "선택되지 않음",
        sample_prd: "📝 PRD샘플 생성",
        prd_changes: "📝 PRD 변경 이력",
        live_logs: "📜 실시간 로그",
        no_logs: "아직 로그가 없습니다",
        ai_quota: "🔋 AI 사용량",
        refresh: "🔄",
        connecting: "연결 중...",
        loading_data: "데이터 로딩 중...",
        no_models: "사용 중인 모델 없음",
        reset_calc: "⏱ 리셋: 계산 중...",
        reset_done: "⏱ 리셋 완료 (갱신 대기)",
        reset_eta: "⏱ 리셋까지 %h시간 %m분",
        tg_connect: "📡 텔레그램 연결",
        tg_disconnect: "📡 텔레그램 연결 해제",
        tg_detail: "📬 상세 알림 받기",
        save: "💾 저장",
        settings: "⚙ 설정",
        max_iter: "최대 반복 횟수",
        iter_delay: "작업간 반복 간격 (초)",
        allow_prd_mod: "PRD 수정 허용",
        auto_start: "🚀 PRD 변경 시 자동 시작",
        auto_commit: "🌿 Git Auto Commit (작업별 브랜치 & 머지)",
        auto_del_branch: "🗑 자동 브랜치 폐기 (머지 후 삭제)",
        code_review: "📝 코드 리뷰 (Gemini Flash)",
        auto_push: "🚀 자동 Push (세션 종료 시)",
        auto_install: "⬆ 자동 업데이트 설치",
        check_updates: "🔍 업데이트 확인",
        no_git_cred: "⚠ Git 권한 없음 — 자동 업데이트가 비활성화되어 있습니다.",
        write_prd_ws: "📋 write-prd (워크스페이스)",
        write_prd_global: "📋 write-prd (글로벌)",
        consecutive_errors: "%err (연속 %cnt회)",
        tasks_progress: "%completed / %total tasks (%pct%)",
        update_to: "v%old → v%new",
        update_btn: "⬆ v%version 업데이트",
        media_attached: " <span style=\\"opacity:0.6;\\" title=\\"첨부 미디어 %cnt개\\">📎%cnt</span>",
        iteration_log: "반복 %iter",
        added_log: "+%add",
        removed_log: "-%rem"
    },
    ja: {
        update_available: "🆕 アップデート利用可能",
        update_now: "⬆ 今すぐアップデート",
        error_occurred: "❌ エラー発生",
        on_auto_accept: "ON — 自動承認アクティブ",
        off: "OFF",
        idle: "IDLE",
        running: "RUNNING",
        quota_paused: "QUOTA PAUSED",
        stopping: "STOPPING...",
        current_iteration: "現在の反復",
        start: "▶ 開始",
        stop: "⏹ 停止",
        task_queue: "📬 タスクキュー",
        task_placeholder: "次のタスクを入力...",
        enqueue_task: "📥 タスクを予約",
        start_task: "🚀 タスク開始",
        no_queued_tasks: "予約済みタスクなし",
        task_file: "📋 タスクファイル",
        not_selected: "未選択",
        sample_prd: "📝 サンプルPRD生成",
        prd_changes: "📝 PRD変更履歴",
        live_logs: "📜 ライブログ",
        no_logs: "まだログがありません",
        ai_quota: "🔋 AI クォータ",
        refresh: "🔄",
        connecting: "接続中...",
        loading_data: "データ読込中...",
        no_models: "使用中のモデルなし",
        reset_calc: "⏱ リセット: 計算中...",
        reset_done: "⏱ リセット完了 (更新待ち)",
        reset_eta: "⏱ リセットまで %h時間 %m分",
        tg_connect: "📡 Telegram接続",
        tg_disconnect: "📡 Telegram切断",
        tg_detail: "📬 詳細通知を受け取る",
        save: "💾 保存",
        settings: "⚙ 設定",
        max_iter: "最大反復回数",
        iter_delay: "反復間隔（秒）",
        allow_prd_mod: "PRD変更を許可",
        auto_start: "🚀 PRD変更時に自動開始",
        auto_commit: "🌿 Git 自動コミット",
        auto_del_branch: "🗑 自動ブランチ削除",
        code_review: "📝 コードレビュー (Gemini Flash)",
        auto_push: "🚀 自動Push (セッション終了時)",
        auto_install: "⬆ 自動アップデートインストール",
        check_updates: "🔍 アップデート確認",
        no_git_cred: "⚠ Git権限なし — 自動アップデート無効",
        write_prd_ws: "📋 write-prd (Workspace)",
        write_prd_global: "📋 write-prd (Global)",
        consecutive_errors: "%err (連続%cnt回)",
        tasks_progress: "%completed / %total タスク (%pct%)",
        update_to: "v%old → v%new",
        update_btn: "⬆ v%version アップデート",
        media_attached: " 📎%cnt",
        iteration_log: "反復 %iter",
        added_log: "+%add",
        removed_log: "-%rem"
    },
    "zh-cn": {
        update_available: "🆕 有可用更新",
        update_now: "⬆ 立即更新",
        error_occurred: "❌ 发生错误",
        on_auto_accept: "ON — 自动接受激活",
        off: "OFF",
        idle: "IDLE",
        running: "RUNNING",
        quota_paused: "QUOTA PAUSED",
        stopping: "STOPPING...",
        current_iteration: "当前迭代",
        start: "▶ 开始",
        stop: "⏹ 停止",
        task_queue: "📬 任务队列",
        task_placeholder: "输入下一个任务...",
        enqueue_task: "📥 加入队列",
        start_task: "🚀 开始任务",
        no_queued_tasks: "没有已排队的任务",
        task_file: "📋 任务文件",
        not_selected: "未选择",
        sample_prd: "📝 生成示例 PRD",
        prd_changes: "📝 PRD 修改记录",
        live_logs: "📜 实时日志",
        no_logs: "暂无日志",
        ai_quota: "🔋 AI 配额",
        refresh: "🔄",
        connecting: "连接中...",
        loading_data: "数据加载中...",
        no_models: "没有使用中的模型",
        reset_calc: "⏱ 重置: 计算中...",
        reset_done: "⏱ 重置完成 (等待更新)",
        reset_eta: "⏱ 距离重置 %h 小时 %m 分钟",
        tg_connect: "📡 连接 Telegram",
        tg_disconnect: "📡 断开 Telegram",
        tg_detail: "📬 接收详细通知",
        save: "💾 保存",
        settings: "⚙ 设置",
        max_iter: "最大迭代次数",
        iter_delay: "迭代间隔 (秒)",
        allow_prd_mod: "允许修改 PRD",
        auto_start: "🚀 PRD 修改时自动启动",
        auto_commit: "🌿 自动 Git 提交",
        auto_del_branch: "🗑 自动删除分支",
        code_review: "📝 代码审核 (Gemini Flash)",
        auto_push: "🚀 会话结束时自动 Push",
        auto_install: "⬆ 自动安装更新",
        check_updates: "🔍 检查更新",
        no_git_cred: "⚠ 无 Git 凭证 — 自动更新已禁用。",
        write_prd_ws: "📋 write-prd (工作区)",
        write_prd_global: "📋 write-prd (全局)",
        consecutive_errors: "%err (连续 %cnt 次)",
        tasks_progress: "%completed / %total 任务 (%pct%)",
        update_to: "v%old → v%new",
        update_btn: "⬆ 更新 v%version",
        media_attached: " 📎%cnt",
        iteration_log: "迭代 %iter",
        added_log: "+%add",
        removed_log: "-%rem"
    },
    "zh-tw": {
        update_available: "🆕 有可用更新",
        update_now: "⬆ 立即更新",
        error_occurred: "❌ 發生錯誤",
        on_auto_accept: "ON — 自動接受啟用",
        off: "OFF",
        idle: "IDLE",
        running: "RUNNING",
        quota_paused: "QUOTA PAUSED",
        stopping: "STOPPING...",
        current_iteration: "當前迭代",
        start: "▶ 開始",
        stop: "⏹ 停止",
        task_queue: "📬 任務佇列",
        task_placeholder: "輸入下一個任務...",
        enqueue_task: "📥 加入佇列",
        start_task: "🚀 開始任務",
        no_queued_tasks: "沒有已排隊的任務",
        task_file: "📋 任務文件",
        not_selected: "未選擇",
        sample_prd: "📝 生成範例 PRD",
        prd_changes: "📝 PRD 修改記錄",
        live_logs: "📜 即時日誌",
        no_logs: "暫無日誌",
        ai_quota: "🔋 AI 配額",
        refresh: "🔄",
        connecting: "連接中...",
        loading_data: "數據加載中...",
        no_models: "沒有使用中的模型",
        reset_calc: "⏱ 重置: 計算中...",
        reset_done: "⏱ 重置完成 (等待更新)",
        reset_eta: "⏱ 距離重置 %h 小時 %m 分鐘",
        tg_connect: "📡 連接 Telegram",
        tg_disconnect: "📡 斷開 Telegram",
        tg_detail: "📬 接收詳細通知",
        save: "💾 保存",
        settings: "⚙ 設置",
        max_iter: "最大迭代次數",
        iter_delay: "迭代間隔 (秒)",
        allow_prd_mod: "允許修改 PRD",
        auto_start: "🚀 PRD 修改時自動啟動",
        auto_commit: "🌿 自動 Git 提交",
        auto_del_branch: "🗑 自動刪除分支",
        code_review: "📝 程式碼審查 (Gemini Flash)",
        auto_push: "🚀 會話結束時自動 Push",
        auto_install: "⬆ 自動安裝更新",
        check_updates: "🔍 檢查更新",
        no_git_cred: "⚠ 無 Git 憑證 — 自動更新已停用。",
        write_prd_ws: "📋 write-prd (工作區)",
        write_prd_global: "📋 write-prd (全域)",
        consecutive_errors: "%err (連續 %cnt 次)",
        tasks_progress: "%completed / %total 任務 (%pct%)",
        update_to: "v%old → v%new",
        update_btn: "⬆ 更新 v%version",
        media_attached: " 📎%cnt",
        iteration_log: "迭代 %iter",
        added_log: "+%add",
        removed_log: "-%rem"
    },
    es: {
        update_available: "🆕 Actualización Disponible",
        update_now: "⬆ Actualizar Ahora",
        error_occurred: "❌ Ocurrió un Error",
        on_auto_accept: "ON - Aceptación Automática",
        off: "OFF",
        idle: "IDLE",
        running: "RUNNING",
        quota_paused: "QUOTA PAUSED",
        stopping: "STOPPING...",
        current_iteration: "Iteración Actual",
        start: "▶ Iniciar",
        stop: "⏹ Detener",
        task_queue: "📬 Cola de Tareas",
        task_placeholder: "Ingresa la siguiente tarea...",
        enqueue_task: "📥 Encolar Tarea",
        start_task: "🚀 Iniciar Tarea",
        no_queued_tasks: "No hay tareas encoladas",
        task_file: "📋 Archivo de Tareas",
        not_selected: "No seleccionado",
        sample_prd: "📝 Generar PRD de muestra",
        prd_changes: "📝 Cambios en PRD",
        live_logs: "📜 Registros en Vivo",
        no_logs: "No hay registros aún",
        ai_quota: "🔋 Cuota de IA",
        refresh: "🔄",
        connecting: "Conectando...",
        loading_data: "Cargando datos...",
        no_models: "No hay modelos en uso",
        reset_calc: "⏱ Reinicio: calculando...",
        reset_done: "⏱ Reinicio completo",
        reset_eta: "⏱ Reinicio en %h h %m m",
        tg_connect: "📡 Conectar Telegram",
        tg_disconnect: "📡 Desconectar Telegram",
        tg_detail: "📬 Recibir notificaciones detalladas",
        save: "💾 Guardar",
        settings: "⚙ Configuraciones",
        max_iter: "Máx Iteraciones",
        iter_delay: "Retraso (seg)",
        allow_prd_mod: "Permitir modificar PRD",
        auto_start: "🚀 Auto-inicio al cambiar PRD",
        auto_commit: "🌿 Auto Git Commit",
        auto_del_branch: "🗑 Auto Eliminar Rama",
        code_review: "📝 Revisión de Código",
        auto_push: "🚀 Auto Push",
        auto_install: "⬆ Instalar actualizaciones auto",
        check_updates: "🔍 Buscar Actualizaciones",
        no_git_cred: "⚠ Sin credenciales de Git.",
        write_prd_ws: "📋 write-prd (Workspace)",
        write_prd_global: "📋 write-prd (Global)",
        consecutive_errors: "%err (Consecutivos %cnt)",
        tasks_progress: "%completed / %total tareas (%pct%)",
        update_to: "v%old -> v%new",
        update_btn: "⬆ Actualizar v%version",
        media_attached: " 📎%cnt",
        iteration_log: "Iteración %iter",
        added_log: "+%add",
        removed_log: "-%rem"
    },
    fr: {
        update_available: "🆕 Mise à jour disponible",
        update_now: "⬆ Mettre à jour",
        error_occurred: "❌ Erreur survenue",
        on_auto_accept: "ON - Acceptation Auto",
        off: "OFF",
        idle: "IDLE",
        running: "RUNNING",
        quota_paused: "QUOTA PAUSED",
        stopping: "STOPPING...",
        current_iteration: "Itération actuelle",
        start: "▶ Démarrer",
        stop: "⏹ Arrêter",
        task_queue: "📬 File d'attente",
        task_placeholder: "Entrez la tâche suivante...",
        enqueue_task: "📥 Ajouter à la file",
        start_task: "🚀 Démarrer la tâche",
        no_queued_tasks: "Aucune tâche en file",
        task_file: "📋 Fichier de tâches",
        not_selected: "Non sélectionné",
        sample_prd: "📝 Générer PRD exemple",
        prd_changes: "📝 Changements PRD",
        live_logs: "📜 Logs en direct",
        no_logs: "Aucun log",
        ai_quota: "🔋 Quota IA",
        refresh: "🔄",
        connecting: "Connexion...",
        loading_data: "Chargement...",
        no_models: "Aucun modèle en cours",
        reset_calc: "⏱ Réinitialisation: calcul...",
        reset_done: "⏱ Réinitialisation terminée",
        reset_eta: "⏱ Réinitialisation dans %h h %m m",
        tg_connect: "📡 Connecter Telegram",
        tg_disconnect: "📡 Déconnecter Telegram",
        tg_detail: "📬 Notifications détaillées",
        save: "💾 Enregistrer",
        settings: "⚙ Paramètres",
        max_iter: "Itérations Max",
        iter_delay: "Délai (sec)",
        allow_prd_mod: "Autoriser modif PRD",
        auto_start: "🚀 Démarrage auto sur PRD",
        auto_commit: "🌿 Git Auto Commit",
        auto_del_branch: "🗑 Auto Suppression Branche",
        code_review: "📝 Revue de Code",
        auto_push: "🚀 Auto Push",
        auto_install: "⬆ Installer MAJ auto",
        check_updates: "🔍 Vérifier MAJ",
        no_git_cred: "⚠ Pas de Git.",
        write_prd_ws: "📋 write-prd (Workspace)",
        write_prd_global: "📋 write-prd (Global)",
        consecutive_errors: "%err (%cnt consécutives)",
        tasks_progress: "%completed / %total (%pct%)",
        update_to: "v%old -> v%new",
        update_btn: "⬆ Mettre à jour v%version",
        media_attached: " 📎%cnt",
        iteration_log: "Itération %iter",
        added_log: "+%add",
        removed_log: "-%rem"
    },
    de: {
        update_available: "🆕 Update verfügbar",
        update_now: "⬆ Jetzt aktualisieren",
        error_occurred: "❌ Fehler aufgetreten",
        on_auto_accept: "ON - Auto Accept aktiv",
        off: "OFF",
        idle: "IDLE",
        running: "RUNNING",
        quota_paused: "QUOTA PAUSED",
        stopping: "STOPPING...",
        current_iteration: "Aktuelle Iteration",
        start: "▶ Starten",
        stop: "⏹ Stoppen",
        task_queue: "📬 Warteschlange",
        task_placeholder: "Nächste Aufgabe...",
        enqueue_task: "📥 Einreihen",
        start_task: "🚀 Starten",
        no_queued_tasks: "Keine Aufgaben",
        task_file: "📋 Aufgabendatei",
        not_selected: "Nicht ausgewählt",
        sample_prd: "📝 Beispiel-PRD generieren",
        prd_changes: "📝 PRD-Änderungen",
        live_logs: "📜 Live-Logs",
        no_logs: "Noch keine Logs",
        ai_quota: "🔋 KI-Kontingent",
        refresh: "🔄",
        connecting: "Verbinde...",
        loading_data: "Lade Daten...",
        no_models: "Keine Modelle",
        reset_calc: "⏱ Reset: Berechne...",
        reset_done: "⏱ Reset abgeschlossen",
        reset_eta: "⏱ Reset in %h h %m m",
        tg_connect: "📡 Telegram verbinden",
        tg_disconnect: "📡 Telegram trennen",
        tg_detail: "📬 Detaillierte Benachrichtigungen",
        save: "💾 Speichern",
        settings: "⚙ Einstellungen",
        max_iter: "Max Iterationen",
        iter_delay: "Verzögerung (Sek)",
        allow_prd_mod: "PRD-Änderung erlauben",
        auto_start: "🚀 Autostart bei PRD",
        auto_commit: "🌿 Git Auto Commit",
        auto_del_branch: "🗑 Auto Branch löschen",
        code_review: "📝 Code Review",
        auto_push: "🚀 Auto Push",
        auto_install: "⬆ Auto-Installation",
        check_updates: "🔍 Updates prüfen",
        no_git_cred: "⚠ Keine Git-Rechte.",
        write_prd_ws: "📋 write-prd (Workspace)",
        write_prd_global: "📋 write-prd (Global)",
        consecutive_errors: "%err (%cnt Mal)",
        tasks_progress: "%completed / %total (%pct%)",
        update_to: "v%old -> v%new",
        update_btn: "⬆ Update v%version",
        media_attached: " 📎%cnt",
        iteration_log: "Iteration %iter",
        added_log: "+%add",
        removed_log: "-%rem"
    },
    ru: {
        update_available: "🆕 Доступно обновление",
        update_now: "⬆ Обновить сейчас",
        error_occurred: "❌ Произошла ошибка",
        on_auto_accept: "ON - Авто-принятие",
        off: "OFF",
        idle: "IDLE",
        running: "RUNNING",
        quota_paused: "QUOTA PAUSED",
        stopping: "STOPPING...",
        current_iteration: "Текущая итерация",
        start: "▶ Старт",
        stop: "⏹ Стоп",
        task_queue: "📬 Очередь задач",
        task_placeholder: "Введите задачу...",
        enqueue_task: "📥 В очередь",
        start_task: "🚀 Запуск",
        no_queued_tasks: "Нет задач в очереди",
        task_file: "📋 Файл задач",
        not_selected: "Не выбран",
        sample_prd: "📝 Создать PRD",
        prd_changes: "📝 Изменения PRD",
        live_logs: "📜 Логи онлайн",
        no_logs: "Логов пока нет",
        ai_quota: "🔋 Квота ИИ",
        refresh: "🔄",
        connecting: "Подключение...",
        loading_data: "Загрузка...",
        no_models: "Нет активных",
        reset_calc: "⏱ Сброс: вычисление...",
        reset_done: "⏱ Сброс завершен",
        reset_eta: "⏱ Сброс через %h ч %m м",
        tg_connect: "📡 Подключить Telegram",
        tg_disconnect: "📡 Отключить Telegram",
        tg_detail: "📬 Детальные уведомления",
        save: "💾 Сохранить",
        settings: "⚙ Настройки",
        max_iter: "Макс Итераций",
        iter_delay: "Задержка (сек)",
        allow_prd_mod: "Разрешить изм. PRD",
        auto_start: "🚀 Авто-старт",
        auto_commit: "🌿 Авто Commit",
        auto_del_branch: "🗑 Авто удал. ветку",
        code_review: "📝 Ревью кода",
        auto_push: "🚀 Авто Push",
        auto_install: "⬆ Авто-установка обн.",
        check_updates: "🔍 Проверить",
        no_git_cred: "⚠ Нет доступов Git.",
        write_prd_ws: "📋 write-prd (Workspace)",
        write_prd_global: "📋 write-prd (Global)",
        consecutive_errors: "%err (Подряд %cnt)",
        tasks_progress: "%completed / %total (%pct%)",
        update_to: "v%old -> v%new",
        update_btn: "⬆ Обновить v%version",
        media_attached: " 📎%cnt",
        iteration_log: "Итерация %iter",
        added_log: "+%add",
        removed_log: "-%rem"
    },
    "pt-br": {
        update_available: "🆕 Atualização Disponível",
        update_now: "⬆ Atualizar Agora",
        error_occurred: "❌ Ocorreu um Erro",
        on_auto_accept: "ON - Aceite Automático",
        off: "OFF",
        idle: "IDLE",
        running: "RUNNING",
        quota_paused: "QUOTA PAUSED",
        stopping: "STOPPING...",
        current_iteration: "Iteração Atual",
        start: "▶ Iniciar",
        stop: "⏹ Parar",
        task_queue: "📬 Fila de Tarefas",
        task_placeholder: "Digite a tarefa...",
        enqueue_task: "📥 Adicionar à Fila",
        start_task: "🚀 Iniciar Tarefa",
        no_queued_tasks: "Sem tarefas na fila",
        task_file: "📋 Arquivo de Tarefas",
        not_selected: "Não selecionado",
        sample_prd: "📝 Gerar PRD de amostra",
        prd_changes: "📝 Mudanças PRD",
        live_logs: "📜 Logs ao Vivo",
        no_logs: "Ainda sem logs",
        ai_quota: "🔋 Cota de IA",
        refresh: "🔄",
        connecting: "Conectando...",
        loading_data: "Carregando...",
        no_models: "Sem modelos",
        reset_calc: "⏱ Reset: calculando...",
        reset_done: "⏱ Reset completo",
        reset_eta: "⏱ Reset em %h h %m m",
        tg_connect: "📡 Conectar Telegram",
        tg_disconnect: "📡 Desconectar Telegram",
        tg_detail: "📬 Notificações Detalhadas",
        save: "💾 Salvar",
        settings: "⚙ Configurações",
        max_iter: "Máx Iterações",
        iter_delay: "Atraso (seg)",
        allow_prd_mod: "Modificar PRD",
        auto_start: "🚀 Auto-start",
        auto_commit: "🌿 Auto Git Commit",
        auto_del_branch: "🗑 Auto Deletar Branch",
        code_review: "📝 Verificação de Código",
        auto_push: "🚀 Auto Push",
        auto_install: "⬆ Auto Instalar",
        check_updates: "🔍 Checar updates",
        no_git_cred: "⚠ Sem credenciais Git.",
        write_prd_ws: "📋 write-prd (Workspace)",
        write_prd_global: "📋 write-prd (Global)",
        consecutive_errors: "%err (%cnt seguidos)",
        tasks_progress: "%completed / %total (%pct%)",
        update_to: "v%old -> v%new",
        update_btn: "⬆ Atualizar v%version",
        media_attached: " 📎%cnt",
        iteration_log: "Iteração %iter",
        added_log: "+%add",
        removed_log: "-%rem"
    },
    hi: {
        update_available: "🆕 अपडेट उपलब्ध",
        update_now: "⬆ अभी अपडेट करें",
        error_occurred: "❌ त्रुटि हुई",
        on_auto_accept: "ON - ऑटो एक्सेप्ट",
        off: "OFF",
        idle: "IDLE",
        running: "RUNNING",
        quota_paused: "QUOTA PAUSED",
        stopping: "STOPPING...",
        current_iteration: "वर्तमान पुनरावृत्ति",
        start: "▶ प्रारंभ",
        stop: "⏹ रोकें",
        task_queue: "📬 कार्य कतार",
        task_placeholder: "कार्य दर्ज करें...",
        enqueue_task: "📥 कतारबद्ध करें",
        start_task: "🚀 कार्य शुरू करें",
        no_queued_tasks: "कतार में कार्य नहीं है",
        task_file: "📋 कार्य फ़ाइल",
        not_selected: "चयनित नहीं",
        sample_prd: "📝 पीआरडी (PRD) बनाएं",
        prd_changes: "📝 पीआरडी परिवर्तन",
        live_logs: "📜 लाइव लॉग",
        no_logs: "कोई लॉग नहीं",
        ai_quota: "🔋 एआई कोटा",
        refresh: "🔄",
        connecting: "जुड़ रहा है...",
        loading_data: "लोड हो रहा है...",
        no_models: "कोई मॉडल नहीं",
        reset_calc: "⏱ रीसेट: गणना...",
        reset_done: "⏱ रीसेट पूर्ण",
        reset_eta: "⏱ रीसेट में %h घंटे %m मिनट",
        tg_connect: "📡 टेलीग्राम कनेक्ट",
        tg_disconnect: "📡 टेलीग्राम डिस्कनेक्ट",
        tg_detail: "📬 विस्तृत सूचनाएं लें",
        save: "💾 सहेजें",
        settings: "⚙ सेटिंग्स",
        max_iter: "अधिकतम लूप",
        iter_delay: "पुनरावृत्ति देरी (सेकंड)",
        allow_prd_mod: "पीआरडी संशोधन की अनुमति दें",
        auto_start: "🚀 ऑटो-स्टार्ट पीआरडी",
        auto_commit: "🌿 गिट ऑटो कमिट",
        auto_del_branch: "🗑 ऑटो ब्रांच हटाएं",
        code_review: "📝 कोड समीक्षा",
        auto_push: "🚀 ऑटो पुश",
        auto_install: "⬆ अपडेट स्वत: इंस्टॉल करें",
        check_updates: "🔍 अपडेट जांचें",
        no_git_cred: "⚠ गिट क्रेडेंशियल्स नहीं हैं।",
        write_prd_ws: "📋 write-prd (कार्यस्थान)",
        write_prd_global: "📋 write-prd (ग्लोबल)",
        consecutive_errors: "%err (%cnt बार)",
        tasks_progress: "%completed / %total कार्य (%pct%)",
        update_to: "v%old -> v%new",
        update_btn: "⬆ अपडेट v%version",
        media_attached: " 📎%cnt",
        iteration_log: "पुनरावृत्ति %iter",
        added_log: "+%add",
        removed_log: "-%rem"
    },
    ar: {
        update_available: "تحديث متاح 🆕",
        update_now: "تحديث الآن ⬆",
        error_occurred: "حدث خطأ ❌",
        on_auto_accept: "نشط - قبول تلقائي ON",
        off: "OFF",
        idle: "IDLE",
        running: "RUNNING",
        quota_paused: "QUOTA PAUSED",
        stopping: "STOPPING...",
        current_iteration: "التكرار الحالي",
        start: "بدء ▶",
        stop: "إيقاف ⏹",
        task_queue: "قائمة المهام 📬",
        task_placeholder: "...أدخل المهمة",
        enqueue_task: "أضف للقائمة 📥",
        start_task: "بدء المهمة 🚀",
        no_queued_tasks: "لا توجد مهام في القائمة",
        task_file: "ملف المهام 📋",
        not_selected: "غير محدد",
        sample_prd: "PRD إنشاء عينة 📝",
        prd_changes: "PRD التغييرات 📝",
        live_logs: "السجلات 📜",
        no_logs: "لا سجلات",
        ai_quota: "حصة الذكاء 🔋",
        refresh: "🔄",
        connecting: "...يتصل",
        loading_data: "...جاري التحميل",
        no_models: "لا توجد نماذج",
        reset_calc: "...إعادة التعيين: حساب ⏱",
        reset_done: "إعادة التعيين اكتملت ⏱",
        reset_eta: "دقيقة %m ساعة %h التعيين في ⏱",
        tg_connect: "اتصال تيليجرام 📡",
        tg_disconnect: "قطع تيليجرام 📡",
        tg_detail: "إشعارات مفصلة 📬",
        save: "حفظ 💾",
        settings: "الإعدادات ⚙",
        max_iter: "أقصى التكرارات",
        iter_delay: "الانتظار (ثانية)",
        allow_prd_mod: "PRD تعديل",
        auto_start: "بدء تلقائي 🚀",
        auto_commit: "حفظ تلقائي جيت 🌿",
        auto_del_branch: "مسح مسار العمل 🗑",
        code_review: "مراجعة الكود 📝",
        auto_push: "دفع تلقائي 🚀",
        auto_install: "التثبيت التلقائي للتحديثات ⬆",
        check_updates: "التحقق من التحديثات 🔍",
        no_git_cred: ".أذونات جيت مفقودة ⚠",
        write_prd_ws: "(المسار) write-prd 📋",
        write_prd_global: "(عام) write-prd 📋",
        consecutive_errors: "(متتالي %cnt) %err",
        tasks_progress: "(%pct%) %total / %completed",
        update_to: "v%new <- v%old",
        update_btn: "v%version تحديث ⬆",
        media_attached: " 📎%cnt",
        iteration_log: "التكرار %iter",
        added_log: "+%add",
        removed_log: "-%rem"
    }
};

function getSidebarHtml(webview, langId = 'en') {
    let lang = 'en';
    if(translations[langId]) {
        lang = langId;
    } else {
        const baseLang = langId.split('-')[0];
        if(translations[baseLang]) lang = baseLang;
        else if(translations[langId.toLowerCase()]) lang = langId.toLowerCase();
    }
    const tData = translations[lang] || translations.en;
    
    // JS template string replaces
    function t(key, args) {
        let str = tData[key] || translations.en[key] || key;
        if(args) {
            for(const [k, v] of Object.entries(args)) {
                str = str.replace('%'+k, v);
            }
        }
        return str;
    }
`;

content = content.replace("function getSidebarHtml(webview) {", topReplacement);

// Helper script inject
const scripInject = `<script nonce="\${nonce}">
    const __LOCALES__ = \${JSON.stringify(tData)};
    function t(key, args) {
        let str = __LOCALES__[key] || key;
        if(args) {
            for(const [k, v] of Object.entries(args)) {
                str = str.replace('%'+k, v);
            }
        }
        return str;
    }
    const vscodeApi = acquireVsCodeApi();`;

content = content.replace(`const vscodeApi = acquireVsCodeApi();`, scripInject);

// Text replacements in HTML Template
const replaces = [
    ["🆕 업데이트 가능", "\${t('update_available')}"],
    ["⬆ 지금 업데이트", "\${t('update_now')}"],
    ["❌ 에러 발생", "\${t('error_occurred')}"],
    ["OFF", "\${t('off')}"],
    ["현재 반복", "\${t('current_iteration')}"],
    ["▶ 시작", "\${t('start')}"],
    ["⏹ 정지", "\${t('stop')}"],
    ["📬 작업 큐", "\${t('task_queue')}"],
    ['placeholder="다음 작업 내용을 입력하세요..."', `placeholder="\\\${t('task_placeholder')}"`],
    ["📥 작업 예약", "\${t('enqueue_task')}"],
    ["📋 작업 파일", "\${t('task_file')}"],
    ["선택되지 않음", "\${t('not_selected')}"],
    ["📝 PRD샘플 생성", "\${t('sample_prd')}"],
    ["📝 PRD 변경 이력", "\${t('prd_changes')}"],
    ["📜 실시간 로그", "\${t('live_logs')}"],
    ["아직 로그가 없습니다", "\${t('no_logs')}"],
    ["🔋 AI 사용량", "\${t('ai_quota')}"],
    ["연결 중...", "\${t('connecting')}"],
    ["데이터 로딩 중...", "\${t('loading_data')}"],
    ["📡 텔레그램 연결", "\${t('tg_connect')}"],
    ["📬 상세 알림 받기", "\${t('tg_detail')}"],
    ["💾 저장", "\${t('save')}"],
    ["⚙ 설정", "\${t('settings')}"],
    ["최대 반복 횟수", "\${t('max_iter')}"],
    ["작업간 반복 간격 (초)", "\${t('iter_delay')}"],
    ["PRD 수정 허용", "\${t('allow_prd_mod')}"],
    ["🚀 PRD 변경 시 자동 시작", "\${t('auto_start')}"],
    ["🌿 Git Auto Commit (작업별 브랜치 & 머지)", "\${t('auto_commit')}"],
    ["🗑 자동 브랜치 폐기 (머지 후 삭제)", "\${t('auto_del_branch')}"],
    ["📝 코드 리뷰 (Gemini Flash)", "\${t('code_review')}"],
    ["🚀 자동 Push (세션 종료 시)", "\${t('auto_push')}"],
    ["⬆ 자동 업데이트 설치", "\${t('auto_install')}"],
    ["🔍 업데이트 확인", "\${t('check_updates')}"],
    ["⚠ Git 권한 없음 — 자동 업데이트가 비활성화되어 있습니다.", "\${t('no_git_cred')}"],
    ["📋 write-prd (워크스페이스)", "\${t('write_prd_ws')}"],
    ["📋 write-prd (글로벌)", "\${t('write_prd_global')}"],

    // Client-side JS replacements
    ["'ON — 자동 수락 활성'", "t('on_auto_accept')"],
    ["'OFF'", "t('off')"],
    ["s.lastError + (s.consecutiveErrors > 1 ? ' (연속 ' + s.consecutiveErrors + '회)' : '')",
     "t('consecutive_errors', { err: s.lastError, cnt: s.consecutiveErrors })"],
    ["'RUNNING'", "t('running')"],
    ["'QUOTA PAUSED'", "t('quota_paused')"],
    ["'STOPPING...'", "t('stopping')"],
    ["'IDLE'", "t('idle')"],
    ["s.progress.completed + ' / ' + s.progress.total + ' tasks (' + pct + '%)'", "t('tasks_progress', { completed: s.progress.completed, total: s.progress.total, pct: pct })"],
    ["'선택되지 않음'", "t('not_selected')"],
    ["'v' + s.version + ' → v' + s.updateInfo.version", "t('update_to', { old: s.version, new: s.updateInfo.version })"],
    ["'⬆ v' + escapeHtml(v.version) + ' 업데이트'", "t('update_btn', { version: escapeHtml(v.version) })"],
    ["'📡 텔레그램 연결 해제'", "t('tg_disconnect')"],
    ["'📡 텔레그램 연결'", "t('tg_connect')"],
    ["'<div style=\"opacity:0.4;text-align:center;padding:8px;font-size:11px;\">예약된 작업이 없습니다</div>'", "'<div style=\"opacity:0.4;text-align:center;padding:8px;font-size:11px;\">'+t('no_queued_tasks')+'</div>'"],
    ["' <span style=\"opacity:0.6;\" title=\"첨부 미디어 ' + mediaCount + '개\">📎' + mediaCount + '</span>'", "t('media_attached', {cnt: mediaCount})"],
    ["'🚀 작업 시작'", "t('start_task')"],
    ["'📥 작업 예약'", "t('enqueue_task')"],
    ["'<strong>반복 ' + c.iteration + '</strong> '", "'<strong>'+t('iteration_log', {iter: c.iteration})+'</strong> '"],
    ["'<span style=\"color:var(--success)\">+' + c.added.length + '</span> '", "'<span style=\"color:var(--success)\">'+t('added_log', {add: c.added.length})+'</span> '"],
    ["'<span style=\"color:var(--danger)\">-' + c.removed.length + '</span>'", "'<span style=\"color:var(--danger)\">'+t('removed_log', {rem: c.removed.length})+'</span>'"],
    ["'<div class=\"log-empty\">아직 로그가 없습니다</div>'", "'<div class=\"log-empty\">'+t('no_logs')+'</div>'"],
    ["'<div class=\"quota-empty\">사용 중인 모델 없음</div>'", "'<div class=\"quota-empty\">'+t('no_models')+'</div>'"],
    ["'⏱ 리셋: 계산 중...'", "t('reset_calc')"],
    ["'⏱ 리셋 완료 (갱신 대기)'", "t('reset_done')"],
    ["'⏱ 리셋까지 ' + h + '시간 ' + m + '분'", "t('reset_eta', { h: h, m: m })"]
];

replaces.forEach(pair => {
    let c2 = content.split(pair[0]).join(pair[1]);
    if (c2 === content) {
        console.warn('NOT FOUND:', pair[0]);
    }
    content = c2;
});

fs.writeFileSync(filePath, content, 'utf8');
console.log('done refactoring HTML Template');
