// AutoAntigravity — Progress Tracker
// Manages progress.txt (append-only)

const vscode = require('vscode');
const fs = require('fs');
const path = require('path');


class ProgressTracker {
    /**
     * @param {Function} log - Logging function
     */
    constructor(log) {
        this.log = log;
    }

    /**
     * Get the progress file path
     * @returns {string|null}
     */
    getProgressFilePath() {
        const workspaceFolders = vscode.workspace.workspaceFolders;
        if (!workspaceFolders || workspaceFolders.length === 0) return null;

        const config = vscode.workspace.getConfiguration('autoAntigravity');
        const progressFileName = config.get('ralphLoop.progressFile', 'progress.txt');
        return path.join(workspaceFolders[0].uri.fsPath, progressFileName);
    }

    /**
     * Append progress entry (append-only, never delete)
     * @param {number} iteration - Current iteration number
     * @param {string} taskText - The task that was worked on
     * @param {string} status - 'completed' | 'partial' | 'failed'
     * @param {string} [notes] - Additional notes
     */
    appendProgress(iteration, taskText, status, notes = '') {
        const filePath = this.getProgressFilePath();
        if (!filePath) {
            this.log('[Ralph] Cannot write progress — no workspace folder');
            return;
        }

        const timestamp = new Date().toISOString();
        const separator = '─'.repeat(60);
        let entry = `\n${separator}\n`;
        entry += `Iteration: ${iteration}\n`;
        entry += `Timestamp: ${timestamp}\n`;
        entry += `Task: ${taskText}\n`;
        entry += `Status: ${status}\n`;
        if (notes) {
            entry += `Notes: ${notes}\n`;
        }
        entry += `${separator}\n`;

        try {
            fs.appendFileSync(filePath, entry, 'utf-8');
            this.log(`[Ralph] Progress appended — iteration ${iteration}, status: ${status}`);
        } catch (e) {
            this.log(`[Ralph] Failed to write progress: ${e.message}`);
        }
    }

    /**
     * Initialize progress file with header
     */
    initializeProgressFile() {
        const filePath = this.getProgressFilePath();
        if (!filePath) return;

        if (!fs.existsSync(filePath)) {
            const header = `# Ralph Loop Progress Log\n# Generated by AutoAntigravity\n# Started: ${new Date().toISOString()}\n`;
            fs.writeFileSync(filePath, header, 'utf-8');
            this.log('[Ralph] Created progress file');
        }
    }

    /**
     * Get the last recorded iteration number
     * @returns {number}
     */
    getLastIteration() {
        const filePath = this.getProgressFilePath();
        if (!filePath || !fs.existsSync(filePath)) return 0;

        const content = fs.readFileSync(filePath, 'utf-8');
        const matches = content.match(/Iteration:\s*(\d+)/g);
        if (!matches || matches.length === 0) return 0;

        const lastMatch = matches[matches.length - 1];
        const num = parseInt(lastMatch.replace('Iteration:', '').trim(), 10);
        return isNaN(num) ? 0 : num;
    }


}

module.exports = { ProgressTracker };
